<?php /** @var $this Creativestyle_SMTP_Block_Adminhtml_System_Config_Field_Password */ ?>
<tr id="row_<?php echo $this->getElement()->getId();?>">
    <td class="label"><?php echo $this->getElement()->getLabel();?></td>
    <td class="value">
        <input style="width:248px;float: left;" value="<?php echo $this->getElement()->getValue();?>" id="<?php echo $this->getElement()->getId();?>" name="<?php echo $this->getElement()->getName();?>"  class="input-text" type="password">
        <button style="height:20px;margin: 0;" class="btn-chooser" onclick="togglePasswordField($('<?php echo $this->getElement()->getId();?>'));return false;">★</button>
    </td>
</tr>

<script type="text/javascript">
    function togglePasswordField(el){
        if($(el).getAttribute('type')=='password'){
            $(el).setAttribute('type', 'text');
        } else {
            $(el).setAttribute('type', 'password');
        }
    }
</script>